METEOR_SCALING = 0.35
PLAYER_SCALING = 0.7

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 400

OUTPUT_WIDTH = 90
OUTPUT_HEIGHT = 60

SCREEN_TITLE = "METEORS"

MOVEMENT_SPEED = 5
ANGLE_CHANGE_SPEED = 1

METEOR_SPAWN_FRAME_LOW = 30
METEOR_SPAWN_FRAME_HIGH = 50

ROCKET_RANGE_LIMIT = 10

METEOR_SPAWN_DIST_FROM_RIGHT_MARGIN = 50
ACCELERATION_X_MULTIPLIER = 1.0/30
ACCELERATION_Y_MULTIPLIER = 1.0/20

SCREEN_SCORE_HEIGHT = 20

HORIZONTAL_VELOCITY_LOW = -6
HORIZONTAL_VELOCITY_HIGH = -4

UPDATE_RATE = 60
UPDATE_RATE_RL = 1

STATUS_RUNNING = 0
STATUS_PAUSED = 1
STATUS_ENDED = 3
STATUS_END_ANIMATION = 4

PRINT_FPS = False

METEORS_IMAGES = ['meteorBrown_big1.png', 'meteorBrown_big2.png', 'meteorBrown_big3.png', 'meteorBrown_big4.png',
                  'meteorGrey_big1.png', 'meteorGrey_big2.png', 'meteorGrey_big3.png', 'meteorGrey_big4.png']

INPUT_SHAPE = (4, 60, 90)
N_ACTIONS = 9